# Generated by Django 5.2.4 on 2025-07-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='einsatzort',
            old_name='einsatzbezeichnung',
            new_name='ort',
        ),
        migrations.RenameField(
            model_name='einsatzort',
            old_name='verantwortlicher',
            new_name='traegername',
        ),
        migrations.AddField(
            model_name='einsatz',
            name='einsatzbezeichnung',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='einsatz',
            name='verantwortlicher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='einsatzort',
            name='plz',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='einsatzort',
            name='adresse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
