# Generated by Django 5.2.4 on 2025-07-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_rename_einsatzbezeichnung_einsatzort_ort_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokument',
            name='datei',
            field=models.FileField(upload_to='diakon_dokumente/{{diakon.personalnummer}}/'),
        ),
    ]
