# Generated by Django 5.2.4 on 2025-07-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_alter_dokument_datei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokument',
            name='datei',
            field=models.FileField(upload_to='diakon_dokumente/{diakon.personalnummer}/'),
        ),
    ]
