# Generated by Django 5.2.4 on 2025-07-10 20:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_alter_einsatz_diakon'),
    ]

    operations = [
        migrations.AddField(
            model_name='diakon',
            name='aktualisiert_durch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diakon_aktualisierer', to='personal.mitarbeiter'),
        ),
        migrations.AddField(
            model_name='diakon',
            name='erstellt_am',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='diakon',
            name='erstellt_durch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diakon_ersteller', to='personal.mitarbeiter'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='kontaktgrund',
            field=models.CharField(choices=[('allgemein', 'Allgemein'), ('versetzung', 'Versetzung'), ('teildienst', 'Teildienst'), ('beurlaubung', 'Beurlaubung'), ('beförderung', 'Beförderung'), ('krankheit', 'Krankheit'), ('fortbildung', 'Fortbildung'), ('ruhestand', 'Ruhestand'), ('besoldung', 'Besoldung'), ('rechtliches', 'Rechtliches'), ('problematik', 'Problematik'), ('sonstiges', 'Sonstiges')], max_length=20),
        ),
        migrations.CreateModel(
            name='Pkua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_add', models.DateField(auto_now_add=True)),
                ('besprochenes_thema', models.CharField(blank=True, max_length=100, null=True)),
                ('beschluss', models.TextField(blank=True, null=True)),
                ('pk_protokoll', models.BooleanField(default=False)),
                ('diakon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pkua_diakone', to='personal.diakon')),
                ('einsatz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pkua_einsaetze', to='personal.einsatz')),
                ('erfasser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pkua_erfasser', to='personal.mitarbeiter')),
                ('kontakt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pkua_kontakte', to='personal.kontakt')),
            ],
        ),
    ]
