# Generated by Django 5.2.4 on 2025-07-10 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_diakon_aktualisiert_durch_diakon_erstellt_am_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diakon',
            name='aktualisiert_durch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diakon_aktualisierer', to='personal.mitarbeiter'),
        ),
    ]
