# Generated by Django 5.2.4 on 2025-07-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_alter_diakon_aktualisiert_durch'),
    ]

    operations = [
        migrations.AddField(
            model_name='diakon',
            name='mobil',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
