# Generated by Django 5.2.4 on 2025-07-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_diakon_mobil'),
    ]

    operations = [
        migrations.AddField(
            model_name='einsatzort',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='einsatzort',
            name='fax',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='einsatzort',
            name='telefon',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
