# Generated by Django 5.2.4 on 2025-07-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_einsatzort_email_einsatzort_fax_einsatzort_telefon'),
    ]

    operations = [
        migrations.AddField(
            model_name='einsatz',
            name='umfang',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
