# Generated by Django 5.2.4 on 2025-07-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_einsatz_umfang'),
    ]

    operations = [
        migrations.AddField(
            model_name='einsatzort',
            name='traegerform',
            field=models.CharField(choices=[('elkb', 'ELKB'), ('diak_traeger', 'Diakonischer Träger'), ('sonst_traeger', 'Sonstiger Träger')], default='ELKB', max_length=20),
        ),
    ]
